### ISSUE TITLE
unable to find inputfile.pdf

### ISSUE THREAD

**Issue by tagorenavabothu** [Nikhilkoneru/Hod.Life#1]
[Errno 2] No such file or directory: u'/home/hod-tt-01/Downloads/Hod.Life-master/download/inputfile.pdf'
[Errno 2] No such file or directory: u'/home/hod-tt-01/Downloads/Hod.Life-master/download/inputfile.pdf'
[Errno 2] No such file or directory: u'/home/hod-tt-01/Downloads/Hod.Life-master/download/inputfile.pdf'
[Errno 2] No such file or directory: u'/home/hod-tt-01/Downloads/Hod.Life-master/download/inputfile.pdf'
[Errno 2] No such file or directory: u'/home/hod-tt-01/Downloads/Hod.Life-master/output/inputfile.pdf'
[Errno 2] No such file or directory: u'/home/hod-tt-01/Downloads/Hod.Life-master/output/inputfile.pdf'

**Comment by Nikhilkoneru** [comment]
Hi Sir, I uploaded this repo
Issue: Forget to upload downloads and output folders in project (Project will use these folders for temporary storage of downloaded pdfs)
Please Download full repo again :-)
